# Generated by Django 3.2.13 on 2023-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDesk', '0002_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
