# Generated by Django 4.2.5 on 2023-09-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HelpDesk", "0004_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="resolve_action",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
