# Generated by Django 4.2.5 on 2023-09-28 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HelpDesk", "0005_request_resolve_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="assigned_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="resolved_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
