# Generated by Django 3.2.13 on 2023-09-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_number', models.IntegerField()),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
