# Generated by Django 3.2.13 on 2023-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sincalculation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
