# Generated by Django 3.2.13 on 2023-09-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sincalc', '0002_sincalculation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sincalculation',
            name='time',
        ),
    ]
