# Generated by Django 3.2.13 on 2023-09-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincalc', '0003_remove_sincalculation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sincalculation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
