# Generated by Django 3.2.13 on 2023-09-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sincalc', '0005_remove_sincalculation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sincalculation',
            old_name='date',
            new_name='created_at',
        ),
    ]
